<?php

/**
 * This is the model base class for the table "{{tag}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Tag".
 *
 * Columns in table "{{tag}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $uid
 * @property string $name
 * @property string $count
 *
 */
abstract class BaseTag extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{tag}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Tag|Tags', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('uid, count', 'length', 'max'=>10),
			array('name', 'length', 'max'=>200),
			array('uid, name, count', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, uid, name, count', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'uid' => Yii::t('app', 'Uid'),
			'name' => Yii::t('app', 'Name'),
			'count' => Yii::t('app', 'Count'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('uid', $this->uid, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('count', $this->count, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}